### ISSUE TITLE
`parse_html_custom` looks non-functional

### ISSUE THREAD

**Issue by droundy** [Adonai/html2md#1] opened 2019-01-03 23:38 UTC
It looks like `parse_html_custom` cannot be made to work, because the `Handle` type used by the `handle` method is private, and the `StructuredPrinter` type also used by `handle` and `after_handle` has no public methods (beyond printing with `Debug`).

Am I correct that the custom parsing is a work in progress?

**Comment by Adonai** [comment] 2019-01-27 19:36
Try again, with v. 0.2.6

**Comment by mckinney-subgraph** [comment] 2019-02-12 00:35
Hi, I also encountered this problem. I tried with v0.2.6 but the problem is still there.

**Comment by Adonai** [comment] 2019-02-12 13:10
@mckinney-subgraph , what issue do you have? What traits/classes are unusable? I'll fix it right away.

**Comment by mckinney-subgraph** [comment] 2019-02-12 14:29
@Adonai I wasn't able to call the methods of StructuredPrinter (insert_str, etc..) due to them being private when using my own TagHandler.

**Comment by Adonai** [comment] 2019-02-12 23:34
Try with 0.2.7

**Comment by mckinney-subgraph** [comment] 2019-02-13 14:52
Thanks @Adonai, 0.2.7 seems to have done the trick :)

**Comment by Adonai** [comment] 2019-02-13 19:30
Great. I'm closing this, feel free to comment if you need to reopen it.

**Closed by Adonai** 2019-02-13 19:30 UTC
